=== Piskvor/game-of-life/life.dtd
<!ELEMENT life (world,organisms)>
<!ELEMENT world (cells,species,iterations)>
<!ELEMENT organisms (organism*)>
<!ELEMENT organism (x_pos,y_pos,species)>
<!ELEMENT x_pos (#PCDATA)>
<!ELEMENT y_pos (#PCDATA)>
<!ELEMENT species (#PCDATA)>
<!ELEMENT cells (#PCDATA)>
<!ELEMENT iterations (#PCDATA)>

=== Piskvor/game-of-life/example-input.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE life SYSTEM "https://piskvor.github.io/game-of-life/life.dtd">
<life>
    <world>

        <cells>20</cells><!-- // Dimension of the square "world" -->

        <species>3</species><!--// Number of distinct species -->

        <iterations>400</iterations><!-- // Number of iterations to be calculated -->
    </world>
    <organisms>

        <!-- glider start -->
        <organism>

            <x_pos>2</x_pos><!-- // x position -->

            <y_pos>1</y_pos><!-- // y position -->

            <species>t</species><!-- // Species type -->

        </organism>
        <organism>

            <x_pos>3</x_pos><!-- // x position -->

            <y_pos>2</y_pos><!-- // y position -->

            <species>t</species><!-- // Species type -->

        </organism>
        <organism>

            <x_pos>1</x_pos><!-- // x position -->

            <y_pos>3</y_pos><!-- // y position -->

            <species>t</species><!-- // Species type -->

        </organism>
        <organism>

            <x_pos>2</x_pos><!-- // x position -->

            <y_pos>3</y_pos><!-- // y position -->

            <species>t</species><!-- // Species type -->

        </organism>
        <organism>

            <x_pos>3</x_pos><!-- // x position -->

            <y_pos>3</y_pos><!-- // y position -->

            <species>t</species><!-- // Species type -->

        </organism>
        <!-- glider end -->
    </organisms>
</life>
